forge 'https://forgeapi.puppetlabs.com'

mod 'stahnma/epel'
mod 'crayfishx/firewalld'
mod 'jlambert121/trusted_ca'
mod 'puppet/archive'
mod 'puppetlabs/java_ks'
mod 'puppetlabs/stdlib', '4.12.0'
mod 'puppetlabs/postgresql'
mod 'mthibaut/users'

mod 'ebrc/ebrc_yum_repo',
  :git => 'git@github.com:EuPathDB/puppet-ebrc_yum_repo.git'

mod 'ebrc/ebrc_java',
  :git => 'git@github.com:EuPathDB/puppet-ebrc_java.git'

mod 'ebrc/ebrc_jenkins',
  :git => 'git@github.com:EuPathDB/puppet-ebrc_jenkins.git'

mod 'ebrc/irods',
  :git => 'git@github.com:EuPathDB/puppet-irods.git'

mod 'ebrc/ebrc_maven',
  :git => 'git@github.com:EuPathDB/puppet-ebrc_maven.git'

mod 'local/profiles',
  :path => './src/profiles'
  :latest
